### ISSUE TITLE
Container and pickable

### ISSUE THREAD

**Issue by SuperFola** [SuperFola/pataro#4]
I'm currently implementing containers and pickable components for the actor class, but encountering a problem:
* the pickable component should remove the owning actor from the current level where it is, thus destroy it
* the container should copy the new actor to hold it and ensures that it can continue to exist (pointer lifetime)
* the remove() method of the container should be able to discard an entity, currently working with an internal identifier per actor

This leads to a problem, actors should be copiable, will keeping their id in some cases.

I think the best thing to do would be to copy actors inside the container, in a `vector<Actor>`, and then search for them by, because storing `vector<Actor*>` would be very yanky as we would need to "remove" the actor from the map while not removing it to keep it alive (the map has a `vector<shared_ptr<Actor>>` actors collection **but** we can't access the shared pointer to copy it into the container).

I'm open to suggestions, currently I'm leaving this as is (an id() method), even though this includes the need to be able to clone in a polymorphic way the actor's components (doable, but need to have a virtual clone() method in every class).

**Comment by HexDecimal** [comment]
Containers seem to be a component that holds Actors.  A more generic term like Entity might be appropriate instead of Actor if it's going to be a catch-all object.

It isn't clear to me why any actor component should be responsible for removing an actor/entity from anything other than its own contents.

The following video can give a better idea on how the core architecture might be implemented:
[Bob Nystrom - Is There More to Game Architecture than ECS?](https://www.youtube.com/watch?v=JxI3Eu5DPwE)

According to that video `Pickable` should be a type of action rather than a component.  This should solve its scope issues.

The use of `shared_ptr` here it seems to be making it harder to keep track of ownership.  Where it'd be more clear what owns what if `unique_ptr` were used exclusively.

**Comment by SuperFola** [comment]
> Containers seem to be a component that holds Actors. A more generic term like Entity might be appropriate instead of Actor if it's going to be a catch-all object.

Yes, I went with Actor at the start and quickly it mutated into something else, will rename it as suggested.

> It isn't clear to me why any actor component should be responsible for removing an actor/entity from anything other than its own contents.

Yes, to me the actor/entity should apply the effect but the way the actor/entity is discarded should be left up to the engine / piece of code that triggered the action, it would be better this way.

Also, pickable isn't a good name because it's more like a component describing the properties of an entity like "healing potion" or "magic scroll".

Will have a look at the video, thanks!

> The use of shared_ptr here it seems to be making it harder to keep track of ownership. Where it'd be more clear what owns what if unique_ptr were used exclusively.

The thing here is that the player is owned by the engine, and they are then put into the level/floor when the game starts, then when they change level/floor, they are removed and put into the next, etc. Thus using shared_ptr here was a better way to achieve that.

**Comment by SuperFola** [comment]
Forgot to mention it but this is now fixed with the new action/use design
